# Generated by Django 4.0.4 on 2022-05-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='xlsx_uploads/%y/%m')),
            ],
        ),
    ]
