# Generated by Django 4.0.4 on 2022-05-05 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UploadApp', '0003_alter_bills_client_org_alter_bills_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='client_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='UploadApp.client', verbose_name='Клиент'),
        ),
    ]
