# Generated by Django 4.0.4 on 2022-05-05 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UploadApp', '0004_alter_organization_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='client_org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='UploadApp.organization', verbose_name='Организация'),
        ),
    ]
