# Generated by Django 4.0.4 on 2022-05-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadApp', '0005_alter_bills_client_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='bill_number',
            field=models.IntegerField(max_length=15, verbose_name='Номер счета клиента'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Организация'),
        ),
        migrations.AlterUniqueTogether(
            name='bills',
            unique_together={('client_org', 'bill_number')},
        ),
        migrations.AlterUniqueTogether(
            name='organization',
            unique_together={('name', 'client_name')},
        ),
    ]
