# Generated by Django 4.0.4 on 2022-05-05 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UploadApp', '0007_rename_name_organization_org_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='client_org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='UploadApp.organization', verbose_name='Организация'),
        ),
    ]
